name: Python package

on: 
  push:
    branches:
      - "master"
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:  ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: prepare
      run: |
        python3 -m pip install --upgrade pip
        pip install .[dev]
    - name: linter (flake8)
      run: flake8
    - name: build
      run: python3 -m build --sdist --wheel
    - name: install
      run: python3 -m pip install --user dist/*.whl
    - name: test (installed)
      run: |
        pysymbolcheck --help
        tar -tvf dist/pysymbolcheck-*.tar.gz | grep LICENSE
        tar -tvf dist/pysymbolcheck-*.tar.gz | grep README.md
